# Oracle Database Connection Settings
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=myuser
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate settings
# For development: allow Hibernate to update schema to match entities (use with caution)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Spring Mail (Gmail SMTP)	
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=andrasbihari06@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enabl=false
# spring.mail.properties.mail.smtp.socketFactory.port=465
# spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
# spring.mail.properties.mail.smtp.socketFactory.fallback=false

# 3. ÚJ SOROK: Megbízunk az smtp.gmail.com címben, átlépve a PKIX tanúsítvány-hibát
# spring.mail.properties.mail.smtp.ssl.trust=*
# spring.mail.properties.mail.smtp.ssl.checkserveridentity=false